### ISSUE TITLE
ValueError: need more than 2 values to unpack

### ISSUE THREAD

**Issue by snknitin** [guxd/VariationalSeq2Seq#3]
/model.py", line 77, in forward
    batch_size, seq_len, emb_sz=input.size()

**Comment by guxd** [comment]
I tried to fix this problem. Could you pull and run again?

**Comment by snknitin** [comment]
It seemed to work but fails after iteration 90

**Comment by snknitin** [comment]
iter 90/120000  step_time:4s  total_time:0m 49s (- 1101m 19s) tol_loss: 440.5102 kl_loss: 493.4261 dec_loss: 5.5693
Traceback (most recent call last):
  File "main.py", line 269, in <module>
    save_every=save_every, sample_every=sample_every, print_every=print_every, learning_rate=learning_rate)
  File "main.py", line 159, in train
    sampled_sentence = sample(embedder, encoder, hidvar, decoder, question, vocab)
  File "main.py", line 205, in sample
    decoder_input, decoder_hidden)
  File "/home/nsamala/miniconda2/envs/pytorch-py2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/nfs/scratch1/nsamala/dialogsystems/latentvarseq2seq/VariationalSeq2Seq/model.py", line 77, in forward
    batch_size, seq_len, emb_sz=input.size()
ValueError: need more than 2 values to unpack
Closing remaining open files:./data/train.h5...done

**Comment by guxd** [comment]
fixed again
